version: '3.4'

services:

  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest 

  euromonitor.api:
    image: ${DOCKER_REGISTRY-}euromonitor
    build:
      context: .
      dockerfile: Euromonitor.ApI/Dockerfile
    depends_on:
     - sqldata