version: '3.4'

services:

  sqldata:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
    volumes:
      -  ~/.euromonitor-sqldata:/var/opt/mssql

  euromonitor.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionString=Server=sqldata;Database=euromonitordb;User Id=sa;Password=Pass@word
    ports:
      - "32769:80"
      - "9350:443"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
 
